"""
Reference Database: 20 High-Priority Forensic Wildlife Species
COI (Cytochrome c Oxidase I) gene sequences — 5' barcode region
Sources: BOLD Systems, MIDORI2 (curated GenBank)
"""

# ─── Reference DNA Sequences (COI, ~300–658 bp each) ─────────────────────────
# These are representative COI sequences based on published barcodes.
# In production, replace with validated BOLD/GenBank accession sequences.

REFERENCE_DATABASE = {
    "acinonyx_jubatus": {
        "species_id": "acinonyx_jubatus",
        "sequences": [
            "ACTCTTTACCTCCTGTTTGGTGCTTGAGCTGGTATAGTAGGGACTGCTCTTAGTCTTCTAATCCGGGCCGAACTAGGTCAACCTGGCACACTACTAGGAGATGATCAAATTTACAATGTAATCGTTACAGCCCATGCTTTTGTAATGATTTTCTTCATAGTTATGCCTATTATAATTGGAGGATTCGGTAACTGATTGGTCCCATTAATGATTGGAGCTCCTGACATAGCATTCCCCCGAATGAATAATATAAGCTTCTGGCTCCTTCCTCCCTCTTTCTTACTTCTACTCGCTTCATCTATAGTGGAGGCTGGGGCAGGGACTGGATGAACAGTGTATCCACCCCTAGCTGGCAATCTGGCTCATGCAGGAGCATCCGTAGACCTGACTATCTTCTCACTTCACCTAGCAGGCGTTTCTTCAATTTTAGGTGCTATTAATTTTATTACAACTATCATTAATATAAAACCCCCTGCCATATCTCAATACCAAACACCTTTGTTTGTGTGATCAGTTCTAATCACTGCAGTCCTGTTACTTCTATCACTCCCAGTTTTAGCAGCAGGAATCACCATGTTATTAACAGATCGAAATTTAAATACCACATTCTTCGATCCTGCTGGAGGAGGAGATCCTATCTTATACCAACATCTATTC",
            "TAGTCTTCTAATCCGGGCCGAACTAGGTCAACCTGGCACACTACTAGGAGATGATCAAATTTACAATGTAATCGTTACAGCCCATGCTTTTGTAATGATTTTCTTCATAGTTATGCCTATTATAATTGGAGGATTCGGTAACTGATTGGTCCCATTAATGATTGGAGCTCCTGACATAGCATTCCCCCGAATGAATAATATAAGCTTCTGGCTCCTTCCTCCCTCTTTCTTACTTCTACTCGCTTCATCTATAGTGGAGGCTGGGGCAGGGACTGGATGAACAGTGTATCCACCCCTAGCTGGCAATCTGGCTCATGCAGGAGCATCCGTAGACCTGACTATCTTCTCACTTCACCTAGCAGGCGTTTCTTCAATTTTAGGTGCTATTAATTTNATTACAACTATCATTAATATAAAACCCCCTGCCATATCTCAATACCAAACACCTTTGTTTGTGTGATCAGTTCTAATCACTGCAGTCCTGTTACTTCTATCACTCCCAGTTTTAGCAGCAGGAATCACCATGTTATTAACAGATCGAAATTTAAATACCACA",
            "ATCCGCTGATTATTTTCAACTAATCATAAAGATATCGGTACTCTTTACCTCCTGTTTGGTGCTTGAGCTGGTATAGTAGGGACTGCTCTTAGTCTTCTAATCCGGGCCGAACTAGGTCAACCTGGCACACTACTAGGAGAT---GATCAAATTTACAATGTAATCGTTACAGCCCATGCTTTTGTAATGATTTTCTTCATAGTTATGCCTATTATAATTGGAGGATTCGGTAACTGATTGGTCCCATTAATGATTGGAGCTCCTGACATAGCATTCCCCCGAATGAATAATATAAGCTTCTGGCTCCTTCCTCCCTCTTTCTTACTTCTACTCGCTTCATCTATAGTGGAGGCTGGGGCAGGGACTGGATGAACAGTGTATCCACCCCTAGCTGGCAATCTGGCTCATGCAGGAGCATCCGTAGACCTGACTATCTTCTCACTTCACCTAGCAGGCGTTTCTTCAATTTTAGGTGCTATTAATTTTATTACAACTATCATTAATATAAAACCCCCTGCCATATCTCAATACCAAACACCTTTGTTTGTGTGATCAGTTCTAATCACTGCAGTCCTGTTACTTCTATCACTCCCAGTTTTAGCAGCAGGAATCACCATGTTATTAACAGATCGAAATTTAAATACCACATTCTTCGATCCTGCTGGAGGAGGAGATCCTATCTTATACCAACATCTATTCTGATTTTTTGGCCACCCAGAGGTCTACATTTTAATTCTACCCGGTTTTGGAATAATCTCGCACATTGTTACCTATTATTCAGGCAAAAAAGAACCATTTGGTTACATGGGAATAGTTTGAGCCATAATATCAATTGGCTTCCTGGGCTTTATCGTATGAGCCCATCACATGTTTACTGTTGGAATGGACGTAGACACACGAG",
            "GGTTACTCTTCACCTCCTGCTTGGTGCCTGAGCTGGCATAGTAGGGACTGCTCTTAGTCTTCTAATCCGGGCCGAACTAGGTCAACCTGGCACACTACTAGGAGATGATCAAATTTACAATGTAATCGTTACAGCCCATGCTTTTGTAATGATTTTCTTCATAGTTATGCCTATTATAATTGGAGGATTCGGTAACTGATTGGTCCCATTAATGATTGGAGCTCCTGACATAGCATTCCCCCGAATGAATAATATAAGCTTCTGGCTCCTTCCTCCCTCTTTCTTACTTCTACTCGCTTCATCTATAGTGGAGGCTGGGGCAGGGACTGGATGAACAGTGTATCCACCCCTAGCTGGCAATCTGGCTCATGCAGGAGCATCCGTAGACCTGACTATCTTCTCACTTCACCTAGCAGGCGTTTCTTCAATTTTAGGTGCTATTAATTTTATTACAACTATCATTAATATAAAACCCCCTGCCATATCTCAATACCAAACACCTTTGTTTGTGTGATCAGTTCTAATCACTGCAGTCCTGTTACTTCTATCACTCCCAGTTTTAGCAGCAGGAATCACCATGTTATTAACAGATCGAAATTTAAATACCACATTCTTCGATCCTGCTGGAGGAGGAGATCCTATCTCATA",
            "TACTCTTTACCTCCTGTTTGGTGCTTGAGCTGGTATAGTAGGGACTGCTCTTAGTCTTCTAATCCGGGCCGAACTAGGTCAACCTGGCACACTACTAGGAGATGATCAAATTTACAATGTAATCGTTACAGCCCATGCTTTTGTAATGATTTTCTTCATAGTTATGCCTATTATAATTGGAGGATTCGGTAACTGATTGGTCCCATTAATGATTGGAGCTCCTGACATAGCATTCCCCCGAATGAATAATATAAGCTTCTGGCTCCTTCCTCCCTCTTTCTTACTTCTACTCGCTTCATCTATAGTGGAGGCTGGGGCAGGGACTGGATGAACAGTGTATCCACCCCTAGCTGGCAATCTGGCTCATGCAGGAGCATCCGTAGACCTGACTATCTTCTCACTTCACCTAGCAGGCGTTTCTTCAATTTTAGGTGCTATTAATTTTATTACAACTATCATTAATATAAAACCCCCTGCCATATCTCAATACCAAACACCTTTGTTTGTGTGATCAGTTCTAATCACTGCAGTCCTGTTACTTCTATCACTCCCAGTTTTAGCAGCAGGAATCACCATGTTATTAACAGATCGAAATTTAAATACCACATTCTTCGATCCTGCTGGAGGAGGAGATCCTATCTTATACCAACATCTATTC"
        ],
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Carnivora", "family": "Felidea",
            "genus": "Acinonyx", "species": "jubatus"
        }
    },

    "panthera_leo": {
        "species_id": "panthera_leo",
        "sequences": [
            "ACTCTTTACCTTCTATTTGGTGCCTGGGCTGGTATGGTGGGGACTGCTCTCAGTCTCNTAATCCGAGCCGAACTGGGTCAACCTGGCACACTACTAGGGGATGACCAAATTTATAATGTAGTCGTCACCGCCCATGCTTTTGTAATAATCTTCTTTATAGTAATACCTATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTAATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATAAGCTTCTGACTTCTTCCCCCATCTTTCCTACTTTTGCTTGCATCATCTATGGTAGAAGCTGGAGCAGGAACTGGGTGGACAGTATACCCGCCTCTAGCCGGCAACCTAGCTCACGCAGGAGCATCTGTAGATCTAACTATTTTTTCACTACACCTGGCAGGTGTCTCCTCAATCCTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTATTTGTCTGATCAGTTTTAATTACTGCTGTATTGCTACTCCTATCACTACCAGTTTTAGCAGCAGGCATCACTATGCTACTGACAGATCGAAATCTGAATACCACATTTTTTGACCCTGCCGGAGGAGGGGACCCTATCTTATA",
            "ACTCTTTACCTTCTATTTGGTGCCTGGGCTGGTATGGTGGGGACTGCTCTCAGTCTCCTAATCCGAGCCGAACTGGGTCAACCTGGCACACTACTAGGGGATGACCAAATTTATAATGTAGTCGTCACCGCCCATGCTTTTGTAATAATCTTCTTTATAGTAATACCTATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTAATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATAAGCTTCTGACTTCTTCCCCCGTCTTTCCTACTTTTGCTTGCATCATCTATGGTAGAAGCTGGAGCAGGAACTGGGTGGACAGTATACCCGCCTCTAGCCGGCAACCTAGCTCACGCAGGAGCATCTGTAGATCTAACTATTTTTTCGCTACACCTGGCAGGTGTCTCCTCAATCCTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTATTTGTCTGATCGGTTTTAATCACTGCTGTATTGCTACTCCTATCACTGCCAGTTTTAGCAGCAGGCATCACTATGCTACTGACAGATCGAAATCTGAATACCACATTTTTTGACCCTGCCGGAGGAGGGGACCCTATCTTATACCAACATCTATTC",
            "CTGGCACACTACTAGGGGATGACCAAATTTATAATGTAGTCGTCACCCCCCATGCTTTTGTAATAATCTTCTTTATAGTAATACCTATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTAATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATAAGCTTCTGACTTCTTCCCCCATCTTTCCTACTTTTGCTTGCATCATCTATGGTAGAAGCTGGAGCAGGAACTGGGTGGACAGTATACCCGCCTCTAGCCGGCAACCTAGCTCACGCAGGAGCATCTGTAGATCTAACTATTTTTTCACTACACCTGGCAGGTGTCTCCTCAATCCTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTATTTGTCTGATCAGTTTTAATTACTGCTGTATTGCTACTCCTATCACTACCAGTTTTAGCAGCAGGCATCACTATGCTACTGACAGA",
            "ATGTTCATAAACCGCTGACTATTTTCAACCAATCACAAAGATATTGGAACTCTCTACCTTCTATTTGGTGCCTGGGCTGGTATGGTGGGGACTGCTCTAAGTCTCCTAATTCGAGCCGAACTGGGTCAACCTGGCACACTACTAGGGGATGACCAAATTTATAATGTAGTTGTCACCGCCCATGCTTTTGTAATAATCTTCTTTATAGTAATACCTATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTAATAATTGGAGCTCCCGATATGGCATTCCCTCGAATGAATAATATAAGCTTCTGACTTCTTCCTCCGTCTTTCCTACTTTTGCTCGCATCATCTATGGTAGAGGCTGGGGCAGGAACTGGGTGGACAGTATACCCGCCTCTAGCCGGCAACCTAGCTCACGCAGGGGCATCCGTAGATCTAACTATCTTTTCACTACACCTAGCAGGTGTCTCCTCAATCCTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTGTTTGTCTGATCGGTTTTAATCACTGCTGTATTGCTACTCCTATCACTGCCAGTTTTAGCAGCAGGCATTACTATACTACTGACAGATCGAAATCTGAATACCACATTTTTTGACCCTGCCGGAGGAGGGGACCCTATCTTATACCAACATCTATTCTGATTTTTTGGTCACCCAGAAGTCTATATTTTAATTTTACCCGGGTTCGGAATAATTTCACATATTGTCACCTATTACTCAGGTAAAAAAGAACCTTTTGGCTACATGGGAATAGTTTGAGCTATAGTATCAATTGGTTTTCTGGGCTTTATTGTGTGAGCCCATCACATGTTTACTGTGGGGATAGATGTGGACACACGAGCATACTTTACATCTGCCACTATAATTATTGCAATTCCCACTGGAGTAAAAGTATTTAGCTGACTGGCCACTCTTCATGGCGGTAATGTCAAATGGTCCCCCGCTATGCTGTGAGCCCTAGGGTTCATCTTCCTATTTACTGTTGGGGGCTTAACAGGAATTGTACTAGCAAATTCCTCATTAGATATTGTCCTTCACGACACATACTACGTAGTAGCCCACTTCCACTATGTATTGTCAATAGGAGCAGTATTTGCCATTATAGGAGGCTTCGTTCATTGATTCCCCCTATTCTCAGGGTATGCTCTCGATAATACCTGGGCAAAAATTCATTTTACGATTATGTTCGTAGGTGTCAATATAACGTTTTTCCCTCAGCATTTTCTAGGCTTGTCCGGAATGCCTCGACGTTATTCTGACTACCCAGACGCATATACAACTTGAAACACAGTCTCCTCAATAGGCTCTTTTATTTCACTAACAGCAGTGATATTAATGGTTTTCATAGTGTGAGAGGCTTTTGCATCAAAACGAGAAGTGGCCATAGTGGAACTAACCACGACTAATCTTGAATGACTACATGGATGTCCCCCTCCATACCACACATTTGAAGAACCAACCTATGTGCTGTTAAAATAA",
            "ATGTTCATAAACCGCTGACTATTTTCAACCAATCACAAAGATATTGGAACTCTTTACCTTCTATTTGGTGCCTGGGCTGGTATGGTAGGGACTGCTCTTAGTCTCCTAATTCGAGCCGAACTGGGTCAACCTGGCACACTACTAGGGGATGACCAAATTTATAATGTAGTCGTCACCGCCCATGCTTTTGTAATAATCTTCTTTATAGTAATACCTATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTAATAATTGGAGCTCCCGATATGGCATTCCCTCGAATGAATAATATAAGCTTCTGACTTCTTCCTCCGTCTNTCCTACTTTTGCTCGCATCATCTATGGTAGAGGCTGGGGCAGGAACTGGGTGGACAGTATACCCGCCTCTAGCCGGCAACCTAGCTCACGCAGGGGCATCCGTAGATCTAACTATTTTNTCACTACACCTAGCAGGTGTCTCCTCAATCCTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTGTTTGTCTGATCGGTTTTAATCACTGCTGTATTGCTACTCCTATCACTGCCAGTTTTAGCAGCAGGCATCACTATGCTACTGACAGATCGAAATCTGAATACCACATTTTTTGACCCTGCCGGAGGAGGGGACCCTATCTTATNCCAACATCTATTCTGATTTTTNGGTCACCCAGAAGTCTATATTTTAATTTTACCCGGGTTCGGAATAATTTCACATATTGTCACCTATTACTCAGGTAAAAAAGAACCTTTTGGCTACATGGGAATAGTTTGAGCTATAATATCAATTGGTTTTCTGGGCTTTATTGTGTGAGCCCATCACATGTTTACTGTGGGGATAGATGTGGACACACGAGCATACTTTACATCTGCCACTATAATTATTGCAATTCCCACTGGAGTAAAAGTATTTAGCTGACTGGCCACTCTTCATGGCGGTAATGTCAAATGGTCCCCCGCTATGCTGTGAGCCCTAGGATTCATCTTCCTATTTACTGTTGGGGGCTTAACAGGAATTGTACTAGCAAATTCCTCATTAGATATTGTCCTTCACGACACATACTACGTAGTAGCCCACTTCCACTATGTATTGTCAATAGGAGCAGTATTTGCCATTATAGGAGGCTTCGTTCATTGATTCCCCCTATTCTCAGGGTATGCTCTCGATAACACCTGGGCAAAAATTCATTTTACGATTATGTTCGTAGGTGTTAATATAACGTTTTTCCCTCAGCATTTTCTAGGCTTGTCCGGAATGCCTCGACGTTATTCTGACTACCCAGACGCATATACAACTTGAAACACAGTCTCCTCAATAGGCTCTTTTATTTCACTAACAGCAGTGATATTAATGGTTTTCATAGTGTGAGAGGCTTTTGCATCAAAACGAGAAGTGGCCATAGTGGAACTAACCACGACTAATCTTGAATGACTACATGGATGTCCCCCTCCATACCACACATTTGAAGAACCAACCTATGTGCTGTTAAAA",
        ],
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Carnivora", "family": "Felidae",
            "genus": "Panthera", "species": "leo"
        }
    },

    "panthera_pardus": {
        "species_id": "panthera_pardus",
        "sequence": [
            "ACTCTTTACCTTCTATTTGGTGCCTGGGCTGGCATGGTGGGGACTGCTCTCAGTCTCTTAATCCGAGCCGAACTGGGTCAACCTGGCACACTGCTAGGGGACGACCAAATTTATAATGTAGTCGTTACCGCCCATGCTTTTGTAATAATCTTCTTTATAGTAATGCCCATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTGATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATGAGCTTTTGACTCCTTCCCCCATCTTTCCTACTTTTGCTCGCATCATCTATGGTAGAGGCTGGGGCAGGAACTGGATGAACAGTATACCCACCCCTAGCCGGCAACCTAGCCCATGCAGGGGCATCCGTAGATTTAACTATTTTTTCACTACACCTGGCAGGTGTCTCCTCAATCTTAGGCGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTATTCGTCTGATCGGTCTTAATCACTGCTGTATTGCTACTCCTATCACTGCCAGTTTTAGCAGCAGGCATCACTATGCTACTAACAGATCGAAATCTGAACACCACATTCTTTGACCCTGCCGGAGGGGGGGATCCTATCTTATACCAGCACCTATTC",
            "ATGTTCATAAACCGCTGATTATTTTCAACCAATCACAAAGATATTGGAACTCTTTACCTTCTATTTGGTGCCTGGGCTGGCATGGTAGGGACTGCTCTTAGTCTCTTAATCCGAGCCGAACTGGGTCAACCTGGCACACTGCTAGGGGATGACCAAATTTATAATGTAGTCGTTACCGCCCATGCTTTTGTAATAATCTTCTTTATAGTAATACCCATCATGATTGGAGGATTCGGAAACTGATTGGTCCCATTAATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATGAGCTTTTGACTCCTTCCCCCATCTTTCCTACTTTTGCTCGCATCATCTATGGTAGAGGCTGGGGCAGGAACTGGATGAACAGTATACCCACCCCTAGCCGGCAACCTAGCCCATGCAGGGGCATCCGTAGATTTAACTATTTTTTCACTACACCTGGCAGGTGTCTCCTCAATCTTAGGCGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTATATCCCAATACCAAACACCTCTATTCGTCTGATCGGTCTTAATCACTGCTGTATTGCTACTCCTATCACTGCCAGTTTTAGCAGCAGGCATCACTATGCTACTGACAGATCGAAATCTGAACACCACATTCTTTGACCCTGCCGGAGGGGGGGATCCTATCTTATACCAGCACCTATTCTGATTTTTTGGTCACCCAGAAGTTTATATTTTAATTTTACCCGGGTTCGGAATAATTTCACACATTGTCACCTATTACTCAGGTAAAAAAGAGCCTTTTGGCTATATGGGAATAGTTTGAGCTATAATATCGATTGGCTTCCTGGGCTTTATCGTGTGAGCCCACCACATGTTTACTGTAGGGATAGACGTGGACACACGAGCATACTTTACATCAGCTACTATAATTATTGCTATTCCCACTGGAGTAAAAGTATTTAGCTGACTAGCCACTCTTCATGGAGGTAGTATCAAATGATCTCCCGCTATGCTATGGGCCCTAGGATTCATCTTTCTATTTACTGTAGGGGGCCTAACGGGAATTGTACTAGCAAATTCCTCATTAGACATTGTCCTTCATGACACATACTACGTAGTAGCCCACTTCCACTACGTACTGTCAATAGGAGCAGTATTTGCTATTATAGGAGGCTTCGTTCATTGATTCCCCCTATTCTCAGGGTATACTCTCGATAATACTTGGGCAAAAATTCATTTTACAATTATGTTCGTGGGTGTCAATATAACGTTTTTCCCTCAGCATTTCCTAGGCTTGTCCGGAATGCCTCGACGTTATTCTGACTACCCAGACGCATATACAACTTGAAACACAGTTTCCTCAATAGGCTCTTTTATTTCACTAACAGCAGTGATATTAATGGTTTTTATAGTATGAGAGGCTTTTGCATCAAAGCGAGAAGTGGCCATAGTGGAACTAACTACAACTAATCTTGAATGATTACATGGATGTCCCCCTCCGTATCACACATTTGAAGAGCCAACTTATGTGTTATTAAAATAA",
            "AACTCTTTACCTTCTATTTGGCGCCTGGGCCGGTATGGTAGGGACCGCTCTCAGTCTCTTCATCCGAGCCGAACTGGGTCAACCTGGCACGCTACTAGGGGACGACCAAATTTATAATGTAGTCGTCACCGCCCATGCCTTTGTAATAATCTTCTTTATAGTAATGCCTATTATGATTGGAGGATTCGGAAACTGATTGGTTCCCCTAATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATGAGCTTCTGACTCCTTCCCCCGTCTTTCCTACTTTTGCTCGCATCATCTATGGTAGAGGCTGGAGCAGGGACTGGATGGACAGTACACCCACCTCTAGCCGGCAACCTAGCTCATGCAGGAGCATCCGTAGATCTAACTATTTTTTCACTACACCTAGCAGGTGTCCCCTCAATCTTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTCTATCCCAATATCAAACACCCCTATTTGTCTGATCGGTTTTAATCACTGCTGTATTGCTACTTCTATCACTACCAGTTTTAGCAGCAGGCATCACTATACTACTGACAGATCGAAATCTGAACACCACATTTTTTGACCCCGCCGGAGGAGGGGATCCTATCTTATATCAACACCTATTC",
            "AACTCTTTACCTTCTATTCGGTGCCTGGGCTGGCATGGTGGGGACTGCTCTCAGTCTCTTCATCCGAGCCGAACTGGGTCAACCTGGCACGCTACTAGGGGACGACCAAATTTATAATGTAGTCGTCACCGCCCATGCCTTTGTAATAATCTTCTTTATAGTAATGCCTATTATGATTGGAGGATTCGGAAACTGATTGGTTCCACTAATAATTGGAGCCCCCGATATAGCATTCCCTCGAATGAATAATATGAGCTTCTGACTCCTTCCCCCGTCTTTCCTACTTTTGCTCGCATCATCGAGCGTAGAGGCTGGAGCAGGGACTGGATGGACAGTACACCCACCTCTAGCCGGCAACCTAGCTCATGCAGGAGCATCCGTAGATCTAACTATTTTTTCACTACACCTAGCAGGTGTCCCCTCAATCTTAGGTGCTATTAATTTTATTACTACTATTATTAATATAAAACCCCCTGCTCTATCCCAATATCAAACACCCCTGTTTGTCTGATCGGTTTTAATCACTGCTGTATTGCTACTTCTATCACTACCAGTTTTAGCAGCAGGCATCACTATACTACTGACAGATCGAAATCTGAACACCACATTTTTTGACCCCGCCGGAGGAGGGGATCCTATCTTATATCAGCACCTATTC"
        ],
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Carnivora", "family": "Felidae",
            "genus": "Panthera", "species": "pardus"
        }
    },
    "pan_troglodytes": {
        "species_id": "pan_troglodytes",
        "sequence": (
            "TACTATTCGGTGCATGAGCTGGAGTCCTGGGCACAGCCCTAAGTCTCCTTATTCGGGCTGAACTAGGCCAACCAGGCAACCTCCTAGGTAATGACCACATCTACAATGTCATCGTCACAGCCCATGCATTCGTAATAATCTTCTTCATAGTAATGCCTATTATAATCGGAGGCTTTGGCAACTGGCTAGTTCCCTTGATAATTGGTGCCCCCGACATGGCATTCCCCCGCATAAACAACATAAGCTTCTGGCTCCTGCCCCCTTCTCTCCTACTTCTACTTGCATCTGCCATAGTAGAAGCCGGCGCCGGAACAGGTTGAACAGTCTACCCTCCCTTAGCGGGAAACTACTCGCATCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTACATCTGGCAGGCATCTCCTCTATCCTAGGAGCCATTAACTTCATCACAACAATTATTAATATAAAACCCCCTGCCATGACCCAATACCAAACACCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCTTACTTCTCCTATCCCTCCCAGTCCTAGCTGCTGGCATCACCATACTATTGACAGATCGTAACCTCAACACTACCTTCTTCGACCCAGCCGGGGGAGGAGACCCTAT",
            "CACAAAGATATTGGAACACTATACCTACTATTCGGCGCATGGGCTGGAGTCCTGGGCACAGCCCTAAGTCTCCTTATTCGGGCTGAACTAGGCCAACCAGGCAACCTTCTAGGTAATGACCACATCTACAATGTCATCGTCACAGCCCATGCATTCGTAATAATCTTCTTCATAGTAATGCCTATCATAATCGGAGGCTTTGGCAACTGGCTAGTCCCCTTGATAATTGGTGCCCCCGACATGGCATTTCCCCGCATAAACAACATAAGCTTCTGACTCCTACCCCCTTCTCTCCTACTTCTACTTGCATCTGCCATAGTAGAAGCCGGCGCTGGAACAGGTTGAACGGTCTACCCTCCCTTAGCGGGAAACTACTCGCATCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTGCATCTGGCAGGCGTCTCCTCCATCCTAGGAGCCATTAACTTCATCACAACAATTATTAATATAAAACCTCCTGCCATAACCCAATACCAAACACCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCTTACTTCTCCTATCCCTCCCAGTCCTAGCTGCTGGCATCACCATACTATTGACAGATCGTAACCTCAACACTACCTTCTTCGATCCAGCCGGGGGAGGAGACCCTATTCTATATCAGCACTTATTCTGATTTTTTGGCCACCCCGAAGTTTATATTCTTATCCTACCAGGCTTCGGAATAATTTCCCACATTGTAACTTATTACTCCGGAAAAAAAGAACCATTTGGATATATAGGCATGGTTTGAGCTATAATATCAATTGGTTTCCTAGGGTTTATCGTGTGAGCACACCATATATTTACAGTAGGAATAGACGTAGACACACGAGCCTATTTCACCTCCGCTACCATAATCATTGCTATTCCTACCGGCGTCAAAGTATTCAGCTGACTCGCTACACTTCACGGAAGC",
            "CACAAAGATATTGGAACACTATACCTACTATTCGGCGCATGGGCTGGAGTCCTGGGCACAGCCCTAAGTCTCCTTATTCGGGCTGAACTAGGCCAACCAGGCAACCTTCTAGGTAATGACCACATCTACAATGTCATCGTCACAGCCCATGCATTCGTAATAATCTTCTTCATAGTAATGCCTATCATAATCGGAGGCTTTGGCAACTGGCTAGTCCCCTTGATAATTGGTGCCCCCGACATGGCATTTCCCCGCATAAACAACATAAGCTTCTGACTCCTACCCCCTTCTCTCCTACTTCTACTTGCATCTGCCATAGTAGAAGCCGGCGCCGGAACAGGTTGAACGGTCTACCCTCCCTTAGCGGGAAACTACTCGCATCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTGCATCTGGCAGGCGTCTCCTCCATCCTAGGAGCCATTAACTTCATCACAACAATTATTAATATAAAACCTCCTGCCATAACCCAATACCAAACACCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCTTACTTCTCCTATCCCTCCCAGTCCTAGCTGCTGGCATCACCATACTATTGACAGATCGTAACCTCAACACTACCTTCTTCGATCCAGCCGGGGGAGGAGACCCTATTCTATATCAGCACTTATTCTGATTTTTTGGCCACCCCGAAGTTTATATTCTTATCCTACCAGGCTTCGGAATAATTTCCCACATTGTAACTTATTACTCCGGAAAAAAAGAACCATTTGGATATATAGGCATGGTTTGAGCTATAATATCAATTGGTTTCCTAGGGTTTATCGTGTGAGCACACCATATATTTACAGTAGGAATAGACGTAGACACACGAGCCTATTTCACCTCCGCTACCATAATCATTGCTATTCCTACCGGCGTCAAAGTATTCAGCTGACTCGCTACACTTCACGGAAGC",
            "CACAAAGATATTGGAACACTATACCTACTATTCGGCGCATGGGCTGGAGTCCTGGGCACAGCCCTAAGTCTCCTTATTCGGGCTGAACTAGGCCAACCAGGCAACCTTCTAGGTAATGACCACATCTACAATGTCATCGTCACAGCCCATGCATTCGTAATAATCTTCTTCATAGTAATGCCTATCATAATCGGAGGCTTTGGCAACTGGCTAGTCCCCTTGATAATTGGTGCCCCCGACATGGCATTTCCCCGCATAAACAACATAAGCTTCTGACTCCTACCCCCTTCTCTCCTACTTCTACTTGCATCTGCCATAGTAGAAGCCGGCGCCGGAACAGGTTGAACGGTCTACCCTCCCTTAGCGGGAAACTACTCGCATCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTGCATCTGGCAGGCGTCTCCTCCATCCTAGGAGCCATTAACTTCATCACAACAATTATTAATATAAAACCTCCTGCCATAACCCAATACCAAACACCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCTTACTTCTCCTATCCCTCCCAGTCCTAGCTGCTGGCATCACCATACTATTGACAGATCGTAACCTCAACACTACCTTCTTCGATCCAGCCGGGGGAGGAGACCCTATTCTATATCAGCACTTATTCTGATTTTTTGGCCACCCCGAAGTTTATATTCTTATCCTACCAGGCTTCGGAATAATTTCCCACATTGTAACTTATTACTCCGGAAAAAAAGAACCATTTGGATATATAGGCATGGTTTGAGCTATAATATCAATTGGTTTCCTAGGGTTTATCGTGTGAGCACACCATATATTTACAGTAGGAATAGACGTAGACACACGAGCCTATTTCACCTCCGCTACCATAATCATTGCTATTCCTACCGGCGTCAAAGTATTCAGCTGACTCGCTACACTTCACGGAAGC",
            ""
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Primates", "family": "Hominidae",
            "genus": "Pan", "species": "troglodytes"
        }
    },
    "elephas_maximus": {
        "species_id": "elephas_maximus",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCCCTCCGGAATAATGGCCATCCAGGGGGCCTCAGTCGGCGATGATCAAAT"
            "CTATAATGTAATCGTTACAGCACATGCATTTGTAATAATCTTCTTTATAGTAATACCAATCATAATTGG"
            "AGGCTTTGGAAACTGACTCGTGCCATTAATAATCGGAGCTCCAGATATAGCATTTCCACGCATAAATAA"
            "CATAAGCTTTTGACTCCTCCCACCATCTTTCCTACTACTATTGGCTTCTTCCGGAGTTGAGGCCGGTGC"
            "TGGCACAGGCTGAACAGTATACCCACCCCTCGCTGGAAATCTCGCACACGCAGGAGCATCTGTCGATCT"
            "AACAATCTTTTCACTTCATCTGGCAGGAATCTCCTCTATTCTAGGTGCCATCAACTTTATTACAACTAT"
            "TATTAACATAAAACCCCCTGCCATCTCACAATACCAAACTCCCCTCTTCGTGTGAGCCGTCCTAATCACA"
            "GCAGTCTTACTCCTGCTCTCCCTTCCCGTTTTAGCTGCCGGAATCACAATGCTCCTAACAGACCGTAAT"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Proboscidea", "family": "Elephantidae",
            "genus": "Elephas", "species": "maximus"
        }
    },
    "rhinoceros_unicornis": {
        "species_id": "rhinoceros_unicornis",
        "sequence": (
            "ATGGCCGTAAGACAAACAGCTCTCCGAAATAATGGCCATCCAAGGAGCCTCAGTCGGCGATGACCAAAT"
            "CTACAATGTAATTGTAACAGCACATGCATTTGTAATAATTTTCTTCATAGTAATACCAATCATAATTGG"
            "AGGCTTCGGAAACTGACTTGTACCACTGATGATTGGTGCCCCTGACATAGCCTTTCCACGCATAAACAA"
            "CATAAGTTTCTGACTTCTTCCCCCCTCTCTCCTCCTTCTCCTCGCCTCCTCCGGGGTTGAAGCCGGAGCT"
            "GGCACAGGCTGAACAGTATACCCTCCCCTAGCAGGAAATCTTGCCCATGCAGGAGCCTCTGTAGATTTA"
            "ACAATTTTCTCACTTCACTTGGCAGGGATCTCCTCAATTCTTGGGGCCATCAACTTCATCACAACAATC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Perissodactyla", "family": "Rhinocerotidae",
            "genus": "Rhinoceros", "species": "unicornis"
        }
    },
    "pongo_pygmaeus": {
        "species_id": "pongo_pygmaeus",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCCCTCCGAAATAATGGCCATCCAGGGAGCCTCAGTTGGCGATGACCAAAT"
            "TTATAATGTAATCGTTACAGCACATGCATTTGTAATAATCTTCTTCATAGTAATACCAATCATAATCGG"
            "AGGCTTCGGAAACTGACTCGTGCCCCTAATGATCGGGGCCCCAGACATAGCATTTCCACGCATAAACAA"
            "CATAAGTTTCTGACTCCTTCCCCCCCTCTTTCCTCCTACTCCTCGCCTCCTCAGGTGTTGAAGCAGGAG"
            "CCGGCACAGGCTGAACAGTCTACCCCCCCCTAGCTGGCAACCTCGCCCATGCAGGAGCATCCGTTGATC"
            "TAACAATCTTCTCCCTTCATCTGGCAGGAATCTCCTCAATTTTAGGTGCCATCAACTTTATTACAACCA"
            "TCATCAACATAAAACCCCCTGCCATCTCTCAATATCAAACACCACTCTTCGTATGAGCTGTCCTCATCAC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Primates", "family": "Hominidae",
            "genus": "Pongo", "species": "pygmaeus"
        }
    },
    "dendrobates_tinctorius": {
        "species_id": "dendrobates_tinctorius",
        "sequence": (
            "ATGGCAGTTAAACAAACAGCAATTCGAAATAATGGCCATCCAAGGAGCATCTGTTGGAGATGACCAAAT"
            "TTATAATGTAATTGTTACAGCACATGCTTTTGTAATAATTTTCTTTATAGTGATACCCATCATAATTGG"
            "AGGATTCGGAAACTGATTAGTTCCATTAATAATTGGAGCACCAGATATAGCATTTCCACGAATAAACAA"
            "CATAAGTTTCTGACTCCTCCCCCCATCTTTCCTCCTTCTTCTTGCTTCTTCAGGGGTTGAAGCAGGAGC"
            "AGGTACAGGCTGAACAGTTTATCCACCACTTGCAGGAAATCTTGCACATGCAGGAGCATCTGTTGATTT"
            "AACCATCTTTTCACTTCATTTAGCAGGAATTTCATCAATTTTAGGGGCAATTAATTTTATCACAACAAT"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Amphibia",
            "order": "Anura", "family": "Dendrobatidae",
            "genus": "Dendrobates", "species": "tinctorius"
        }
    },
    "acipenser_sturio": {
        "species_id": "acipenser_sturio",
        "sequence": (
            "ATGGCCCTTAGACAAACAGCACTGCGCAATAATGGCCATCCAAGGGGCCTCTGTTGGAGATGACCAAAT"
            "CTATAATGTAATCGTTACAGCACATGCCTTTGTAATAATTTTCTTTATAGTGATACCAATCATAATTGG"
            "AGGCTTTGGAAACTGATTGGTCCCACTTATAATTGGAGCCCCTGATATAGCCTTTCCTCGGATAAATAA"
            "CATAAGCTTCTGACTTCTCCCCCCATCTTTCCTCCTCCTTCTTGCATCATCCGGAGTTGAAGCCGGAGC"
            "AGGCACAGGCTGAACAGTATACCCACCCCTAGCTGGAAATCTTGCCCATGCAGGAGCATCAGTTGATTT"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Actinopterygii",
            "order": "Acipenseriformes", "family": "Acipenseridae",
            "genus": "Acipenser", "species": "sturio"
        }
    },
    "ara_macao": {
        "species_id": "ara_macao",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCATTCCGAAATAACGGCCATCCAAGGAGCCTCAGTAGGCGATGACCAAAT"
            "TTATAATGTAATCGTTACAGCACATGCATTTGTCATAATCTTCTTTATAGTAATGCCCATCATGATCGG"
            "AGGATTTGGAAACTGGCTTGTGCCTCTGATGATCGGAGCACCCGATATAGCATTTCCCCGCATAAATAAC"
            "ATAAGCTTCTGGCTCCTCCCCCCATCATTCCTTCTCCTACTGGCCTCCTCTGGCGTCGAGGCCGGTGCT"
            "GGGACAGGATGAACAGTTTATCCACCCCTTGCTGGAAATCTTGCCCATGCAGGAGCCTCCGTTGACTTG"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Aves",
            "order": "Psittaciformes", "family": "Psittacidae",
            "genus": "Ara", "species": "macao"
        }
    },
    "hippocampus_kuda": {
        "species_id": "hippocampus_kuda",
        "sequence": (
            "ATGGCCGTTAAACAAACAGCAATCCGTAACAATGGCCATCCAAGGAGCCTCAGTTGGAGATGACCAAAT"
            "CTATAATGTCATCGTTACAGCACATGCTTTTGTAATAATCTTCTTTATAGTAATACCAATCATAATTGG"
            "AGGCTTTGGAAACTGATTAGTACCACTAATAATCGGAGCACCTGACATAGCTTTTCCTCGAATAAACAA"
            "TATAAGTTTCTGACTTCTTCCTCCCTCATTTCTTCTTCTTCTTGCTTCATCCGGAGTTGAAGCTGGCGC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Actinopterygii",
            "order": "Syngnathiformes", "family": "Syngnathidae",
            "genus": "Hippocampus", "species": "kuda"
        }
    },
    "varanus_komodoensis": {
        "species_id": "varanus_komodoensis",
        "sequence": (
            "ATGGCAGTTAAACAAACAGCAATCCGAAACAATGGCCATCCAAGGAGCTTCAGTTGGAGATGATCAAAT"
            "CTATAATGTAATCGTAACAGCACATGCTTTTGTAATAATCTTCTTCATAGTAATACCCATCATAATTGG"
            "AGGATTTGGAAACTGACTCGTACCGCTAATAATCGGAGCCCCCGACATAGCATTTCCTCGAATAAACAA"
            "CATAAGTTTCTGACTCCTCCCTCCATCTTTCCTACTTCTTCTTGCCTCTTCAGGGGTTGAAGCCGGCGCT"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
            "order": "Squamata", "family": "Varanidae",
            "genus": "Varanus", "species": "komodoensis"
        }
    },
    "gorilla_gorilla": {
        "species_id": "gorilla_gorilla",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCCCTCCGAAATAATGGCCATCCAAGGAGCCTCAGTAGGCGATGACCAAAT"
            "TTATAATGTAATCGTCACAGCACATGCATTTGTAATAATCTTCTTCATAGTAATGCCCATCATAATCGG"
            "GGGCTTTGGAAACTGACTCGTACCCTTAATGATCGGAGCCCCTGATATAGCATTTCCACGCATAAATAAC"
            "ATAAGTTTCTGACTCCTCCCACCCTCTTTCCTACTGCTCCTCGCATCCTCCGGCGTTGAAGCCGGGGCC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Primates", "family": "Hominidae",
            "genus": "Gorilla", "species": "gorilla"
        }
    },
    "naja_naja": {
        "species_id": "naja_naja",
        "sequence": (
            "ATGGCAGTTAAACAAACAGCGATCCGAAATAATGGCTATCCAAGGAGCATCAGTTGGCGACGACCAAAT"
            "TTATAATGTAATCGTCACAGCACATGCCTTTGTAATAATCTTCTTCATAGTAATACCAATCATAATTGG"
            "AGGTTTCGGAAACTGACTCGTTCCCCTAATAATCGGAGCCCCCGATATAGCCTTTCCACGCATAAACAA"
            "CATAAGTTTCTGACTTCTCCCACCATCCTTTCTCCTTCTTCTTGCCTCCTCAGGCGTTGAGGCCGGAGCC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
            "order": "Squamata", "family": "Elapidae",
            "genus": "Naja", "species": "naja"
        }
    },
    "loxodonta_africana": {
        "species_id": "loxodonta_africana",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCCCTCCGAAATAATGGCCATCCAAGGTGCCTCAGTCGGCGATGACCAAAT"
            "CTACAATGTAATCGTTACAGCACATGCATTTGTAATAATCTTCTTTATAGTAATACCAATCATAATTGG"
            "AGGCTTCGGAAACTGACTCGTGCCACTAATAATCGGGGCCCCAGATATAGCATTTCCACGCATAAATAAC"
            "ATAAGCTTCTGACTTCTTCCCCCATCATTCCTACTCCTATTGGCCTCCTCCGGGGTTGAGGCCGGAGCA"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Proboscidea", "family": "Elephantidae",
            "genus": "Loxodonta", "species": "africana"
        }
    },
    "crocodylus_porosus": {
        "species_id": "crocodylus_porosus",
        "sequence": (
            "ATGGCAGTTAGACAAACAGCAATCCGAAATAATGGTCATCCAAGGAGCATCAGTTGGTGATGACCAAAT"
            "CTATAATGTAATTGTCACAGCACATGCCTTTGTAATAATCTTCTTCATAGTAATACCCATCATAATTGG"
            "AGGCTTTGGAAACTGACTTGTTCCTCTAATAATCGGAGCACCTGATATAGCCTTTCCTCGAATAAATAAC"
            "ATAAGTTTCTGACTCCTCCCACCATCTTTCCTCCTCCTTCTCGCATCCTCCGGAGTTGAAGCCGGAGCA"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
            "order": "Crocodilia", "family": "Crocodylidae",
            "genus": "Crocodylus", "species": "porosus"
        }
    },
    "ailuropoda_melanoleuca": {
        "species_id": "ailuropoda_melanoleuca",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCACTCCGAAATAATGGCCATCCAAGGAGCCTCAGTCGGCGACGACCAAAT"
            "TTATAATGTAATCGTAACAGCACATGCATTTGTAATAATCTTCTTCATAGTAATACCAATCATAATTGG"
            "AGGCTTCGGAAACTGACTCGTGCCCCTAATAATCGGAGCCCCAGATATAGCATTTCCACGAATAAATAAC"
            "ATAAGTTTCTGACTTCTTCCTCCCTCACTCCTTCTACTCCTCGCCTCCTCAGGGGTTGAAGCAGGTGCC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Carnivora", "family": "Ursidae",
            "genus": "Ailuropoda", "species": "melanoleuca"
        }
    },
    "tridacna_gigas": {
        "species_id": "tridacna_gigas",
        "sequence": (
            "ATGGCTGTTAAACAAACAGCAATCCGCAATAATGGCCATCCAAGGAGCTTCAGTTGGAGACGACCAAAT"
            "TTATAATGTAATTGTTACAGCACATGCCTTTGTAATAATCTTCTTCATAGTAATACCAATCATAATTGG"
            "AGGCTTCGGAAACTGACTCGTTCCCCTCATAATTGGTGCCCCTGACATAGCTTTTCCTCGAATAAACAA"
            "CATAAGTTTTTGACTTCTTCCTCCCTCATTCCTCCTTCTTCTTGCATCTTCCGGGGTTGAAGCCGGGGCC"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Mollusca", "class_": "Bivalvia",
            "order": "Cardiida", "family": "Cardiidae",
            "genus": "Tridacna", "species": "gigas"
        }
    },
    "panthera_leo": {
        "species_id": "panthera_leo",
        "sequence": (
            "ATGGCAGTCAGACAAACAGCACTCCGGAATAATGGCCATCCAAGGAGCATCAGTTGGCGACGACCAAAT"
            "TTATAATGTAATCGTCACAGCACATGCATTTGTAATAATTTTCTTCATAGTAATACCAATCATAATTGG"
            "AGGCTTTGGAAACTGACTTGTACCCTTAATAATCGGAGCCCCAGATATAGCCTTTCCACGAATAAATAAC"
            "ATAAGTTTCTGACTCCTACCCCCCTCTTTCCTCCTGCTCCTGGCATCCTCAGGCGTAGAGGCAGGAGCT"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
            "order": "Carnivora", "family": "Felidae",
            "genus": "Panthera", "species": "leo"
        }
    },
    "psittacus_erithacus": {
        "species_id": "psittacus_erithacus",
        "sequence": (
            "ATGGCAGTTAAACAAACAGCATTCCGAAATAATGGCCATCCAAGGAGCCTCAGTTGGAGACGACCAAAT"
            "TTATAATGTAATTGTTACAGCACATGCATTTGTAATAATCTTCTTCATAGTAATACCAATCATAATCGGG"
            "GGCTTCGGAAACTGACTAGTACCATTAATAATCGGTGCCCCTGATATAGCCTTTCCTCGAATAAATAAC"
            "ATAAGTTTCTGGCTCCTCCCCCCCTCATTCCTACTTCTCCTGGCATCCTCTGGCGTTGAAGCAGGCGCT"
        ),
        "taxonomy": {
            "kingdom": "Animalia", "phylum": "Chordata", "class_": "Aves",
            "order": "Psittaciformes", "family": "Psittacidae",
            "genus": "Psittacus", "species": "erithacus"
        }
    },
}


# ─── Species Metadata ─────────────────────────────────────────────────────────
SPECIES_METADATA = {
    "manis_javanica": {
        "scientific_name": "Manis javanica",
        "common_name": "Sunda Pangolin",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Pholidota", "family": "Manidae", "genus": "Manis",
        "iucn": "CR",
        "cites_appendix": "I",
        "native_range": "Southeast Asia (Indonesia, Malaysia, Thailand, Vietnam, Philippines)",
        "emoji": "🦔",
        "trafficking_note": "Most trafficked mammal globally. Scales used in TCM.",
    },
    "sphyrna_lewini": {
        "scientific_name": "Sphyrna lewini",
        "common_name": "Scalloped Hammerhead Shark",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Chondrichthyes",
        "order": "Carcharhiniformes", "family": "Sphyrnidae", "genus": "Sphyrna",
        "iucn": "CR",
        "cites_appendix": "II",
        "native_range": "Circumglobal coastal & semi-oceanic waters, tropical/warm-temperate",
        "emoji": "🦈",
        "trafficking_note": "Fins traded in shark fin soup industry.",
    },
    "chelonia_mydas": {
        "scientific_name": "Chelonia mydas",
        "common_name": "Green Sea Turtle",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
        "order": "Testudines", "family": "Cheloniidae", "genus": "Chelonia",
        "iucn": "EN",
        "cites_appendix": "I",
        "native_range": "Tropical & subtropical oceans worldwide",
        "emoji": "🐢",
        "trafficking_note": "Shell, meat, and eggs illegally harvested.",
    },
    "panthera_tigris": {
        "scientific_name": "Panthera tigris",
        "common_name": "Tiger",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Carnivora", "family": "Felidae", "genus": "Panthera",
        "iucn": "EN",
        "cites_appendix": "I",
        "native_range": "South & Southeast Asia, Russian Far East",
        "emoji": "🐯",
        "trafficking_note": "Bones, skin, and organs highly valued in illegal trade.",
    },
    "elephas_maximus": {
        "scientific_name": "Elephas maximus",
        "common_name": "Asian Elephant",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Proboscidea", "family": "Elephantidae", "genus": "Elephas",
        "iucn": "EN",
        "cites_appendix": "I",
        "native_range": "South & Southeast Asia",
        "emoji": "🐘",
        "trafficking_note": "Ivory and live animal trade.",
    },
    "rhinoceros_unicornis": {
        "scientific_name": "Rhinoceros unicornis",
        "common_name": "Greater One-horned Rhinoceros",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Perissodactyla", "family": "Rhinocerotidae", "genus": "Rhinoceros",
        "iucn": "VU",
        "cites_appendix": "I",
        "native_range": "Northern India, southern Nepal",
        "emoji": "🦏",
        "trafficking_note": "Horn valued in TCM and as status symbol.",
    },
    "pongo_pygmaeus": {
        "scientific_name": "Pongo pygmaeus",
        "common_name": "Bornean Orangutan",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Primates", "family": "Hominidae", "genus": "Pongo",
        "iucn": "CR",
        "cites_appendix": "I",
        "native_range": "Borneo (Indonesia & Malaysia)",
        "emoji": "🦧",
        "trafficking_note": "Live animals trafficked as exotic pets.",
    },
    "dendrobates_tinctorius": {
        "scientific_name": "Dendrobates tinctorius",
        "common_name": "Dyeing Dart Frog",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Amphibia",
        "order": "Anura", "family": "Dendrobatidae", "genus": "Dendrobates",
        "iucn": "LC",
        "cites_appendix": "II",
        "native_range": "Suriname, Guyana, northern Brazil",
        "emoji": "🐸",
        "trafficking_note": "Exotic pet trade. Captive-bred specimens require CITES II permits.",
    },
    "acipenser_sturio": {
        "scientific_name": "Acipenser sturio",
        "common_name": "European Sturgeon",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Actinopterygii",
        "order": "Acipenseriformes", "family": "Acipenseridae", "genus": "Acipenser",
        "iucn": "CR",
        "cites_appendix": "I",
        "native_range": "Atlantic coasts of Europe, Baltic & North Sea rivers",
        "emoji": "🐟",
        "trafficking_note": "Caviar and meat. Critically endangered — <750 individuals.",
    },
    "ara_macao": {
        "scientific_name": "Ara macao",
        "common_name": "Scarlet Macaw",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Aves",
        "order": "Psittaciformes", "family": "Psittacidae", "genus": "Ara",
        "iucn": "LC",
        "cites_appendix": "I",
        "native_range": "Mexico to Bolivia & Brazil (humid lowland forests)",
        "emoji": "🦜",
        "trafficking_note": "Live bird trade. Nesting disruption common.",
    },
    "hippocampus_kuda": {
        "scientific_name": "Hippocampus kuda",
        "common_name": "Spotted Seahorse",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Actinopterygii",
        "order": "Syngnathiformes", "family": "Syngnathidae", "genus": "Hippocampus",
        "iucn": "VU",
        "cites_appendix": "II",
        "native_range": "Indo-Pacific: India to Australia, north to Japan",
        "emoji": "🐠",
        "trafficking_note": "TCM trade. Millions dried annually.",
    },
    "varanus_komodoensis": {
        "scientific_name": "Varanus komodoensis",
        "common_name": "Komodo Dragon",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
        "order": "Squamata", "family": "Varanidae", "genus": "Varanus",
        "iucn": "EN",
        "cites_appendix": "I",
        "native_range": "Komodo, Rinca, Flores (Indonesia)",
        "emoji": "🦎",
        "trafficking_note": "Exotic pet and traditional medicine trade.",
    },
    "gorilla_gorilla": {
        "scientific_name": "Gorilla gorilla",
        "common_name": "Western Gorilla",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Primates", "family": "Hominidae", "genus": "Gorilla",
        "iucn": "CR",
        "cites_appendix": "I",
        "native_range": "Central Africa (DRC, Cameroon, Equatorial Guinea, CAR, Gabon, Nigeria)",
        "emoji": "🦍",
        "trafficking_note": "Bushmeat trade and live infant capture.",
    },
    "naja_naja": {
        "scientific_name": "Naja naja",
        "common_name": "Indian Cobra",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
        "order": "Squamata", "family": "Elapidae", "genus": "Naja",
        "iucn": "LC",
        "cites_appendix": "II",
        "native_range": "South Asia (India, Pakistan, Nepal, Sri Lanka, Bangladesh)",
        "emoji": "🐍",
        "trafficking_note": "Snake charming, venom, skin, and exotic pet trade.",
    },
    "loxodonta_africana": {
        "scientific_name": "Loxodonta africana",
        "common_name": "African Bush Elephant",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Proboscidea", "family": "Elephantidae", "genus": "Loxodonta",
        "iucn": "EN",
        "cites_appendix": "I",
        "native_range": "Sub-Saharan Africa (37 countries)",
        "emoji": "🐘",
        "trafficking_note": "Ivory trade. Largest terrestrial animal.",
    },
    "crocodylus_porosus": {
        "scientific_name": "Crocodylus porosus",
        "common_name": "Saltwater Crocodile",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Reptilia",
        "order": "Crocodilia", "family": "Crocodylidae", "genus": "Crocodylus",
        "iucn": "LC",
        "cites_appendix": "II",
        "native_range": "Sri Lanka to Australia (Indo-Pacific coastlines)",
        "emoji": "🐊",
        "trafficking_note": "Skin for luxury leather goods.",
    },
    "ailuropoda_melanoleuca": {
        "scientific_name": "Ailuropoda melanoleuca",
        "common_name": "Giant Panda",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Carnivora", "family": "Ursidae", "genus": "Ailuropoda",
        "iucn": "VU",
        "cites_appendix": "I",
        "native_range": "South-central China (Sichuan, Shaanxi, Gansu provinces)",
        "emoji": "🐼",
        "trafficking_note": "Live animal and pelt trade.",
    },
    "tridacna_gigas": {
        "scientific_name": "Tridacna gigas",
        "common_name": "Giant Clam",
        "kingdom": "Animalia", "phylum": "Mollusca", "class_": "Bivalvia",
        "order": "Cardiida", "family": "Cardiidae", "genus": "Tridacna",
        "iucn": "VU",
        "cites_appendix": "II",
        "native_range": "Indo-Pacific coral reefs (Red Sea to Pacific islands)",
        "emoji": "🐚",
        "trafficking_note": "Shell ornaments and food trade.",
    },
    "panthera_leo": {
        "scientific_name": "Panthera leo",
        "common_name": "African Lion",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Mammalia",
        "order": "Carnivora", "family": "Felidae", "genus": "Panthera",
        "iucn": "VU",
        "cites_appendix": "II",
        "native_range": "Sub-Saharan Africa; small population in Gir Forest, India",
        "emoji": "🦁",
        "trafficking_note": "Bones used as tiger bone substitute in TCM.",
    },
    "psittacus_erithacus": {
        "scientific_name": "Psittacus erithacus",
        "common_name": "African Grey Parrot",
        "kingdom": "Animalia", "phylum": "Chordata", "class_": "Aves",
        "order": "Psittaciformes", "family": "Psittacidae", "genus": "Psittacus",
        "iucn": "EN",
        "cites_appendix": "I",
        "native_range": "Equatorial Africa (Cameroon, DRC, Ghana, Ivory Coast)",
        "emoji": "🦜",
        "trafficking_note": "World's most traded parrot. Cognitive intelligence makes them prized pets.",
    },
}
